#! /bin/sh

prefix=/home/jfmrod/usr
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: eutils-config [OPTION]

Known values for OPTION are:

  --prefix		show EUTILS installation prefix 
  --libs		print library linking information
  --cxxflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --version)
	echo 1.1.0
	exit 0
	;;

    --help)
	usage 0
	;;

    --cxxflags)
       	echo -I${prefix}/include -O2 -I/home/jfmrod/usr/include -pthread -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread 
       	;;

    --libs)
       	echo -L/home/jfmrod/usr/lib -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc eutils/libeutils.a -lmpi++ -lmpi_cxx -lrt   -lmpi
       	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
