#! /bin/sh

prefix=/home/jfmrod/usr
exec_prefix=${prefix}
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: eutils-config [OPTION]

Known values for OPTION are:

  --prefix		show EUTILS installation prefix 
  --libs		print library linking information
  --cxxflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --version)
	echo 1.0.0
	exit 0
	;;

    --help)
	usage 0
	;;

    --cxxflags)
       	echo -I${prefix}/include -funroll-loops -O2 -static -pthread -I/home/jfmrod/usr/include -I/home/jfmrod/usr/include -I/home/jfmrod/usr/include/ncurses -I/include 
       	;;

    --libs)
       	echo -static -L/lib eutils/libeutils.a -lreadline -lmpi_cxx -lmpi -lrt  -lopen-rte -lopen-pal -libverbs -lnsl -lutil -lm -ldl -L/home/jfmrod/usr/lib -lgsl -lgslcblas -lm -L/home/jfmrod/usr/lib -lncurses -lgmp -lgmpxx -lmpi -lapophenia -lz -lreadline
       	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
